import type { EntryContext, EntryResult, PublicEntry } from "../shared/entries"
import type { Credentials } from "./credentials"
import { PasteError } from "./paste-client"
import type { PasteClient } from "./paste-client"
import type { Binding, BindingStore, Operation } from "./store"

function identifier(value: unknown): value is string {
  return (
    typeof value === "string" &&
    value.length > 0 &&
    value.length <= 256 &&
    Array.from(value).every((char) => char.charCodeAt(0) >= 32)
  )
}

export class EntryService {
  constructor(
    private readonly store: BindingStore,
    private readonly credentials: Credentials,
    private readonly client: PasteClient,
  ) {}

  private error(code: string, correlationId: string = crypto.randomUUID(), retryable = false): EntryResult {
    return { ok: false, code, correlationId, retryable }
  }

  private project(binding: Binding, version = binding.version): PublicEntry {
    if (!binding.paste_name) throw new Error("ENTRY_NOT_READY")
    return {
      id: binding.id,
      pasteName: binding.paste_name,
      publicUrl: this.client.publicUrl(binding.paste_name),
      visibility: "active",
      retentionMode: "permanent",
      expiresAt: null,
      version,
    }
  }

  private duplicate(op: Operation, fingerprint: string): EntryResult {
    if (op.fingerprint !== fingerprint) return this.error("REQUEST_CONFLICT", op.id)
    if (op.status !== "succeeded" || !op.result) return this.error("RECONCILIATION_REQUIRED", op.id)
    // Results are generated by project(), never from upstream response objects.
    return { ok: true, entry: JSON.parse(op.result) as PublicEntry }
  }

  private async operation(
    scope: string,
    request: string,
    entry: string,
    kind: "create" | "update",
    fingerprint: string,
    content: string,
    version: number,
  ): Promise<Operation> {
    return {
      id: crypto.randomUUID(),
      scope_id: scope,
      request_id: request,
      entry_id: entry,
      kind,
      fingerprint,
      content_fingerprint: await this.credentials.fingerprint(content),
      expected_version: version,
      status: "reserved",
      result: null,
    }
  }

  async createEntry(
    context: EntryContext,
    input: { recordKey: string; requestId: string; content: string },
  ): Promise<EntryResult> {
    if (
      !identifier(context.scopeId) ||
      !identifier(input.recordKey) ||
      !identifier(input.requestId) ||
      typeof input.content !== "string"
    )
      return this.error("INVALID_INPUT")
    try {
      const fingerprint = await this.credentials.fingerprint(
        JSON.stringify(["create", context.scopeId, input.recordKey, input.content]),
      )
      const existing = await this.store.operation(context.scopeId, input.requestId)
      if (existing) return this.duplicate(existing, fingerprint)
      const id = crypto.randomUUID()
      const password = this.credentials.generate()
      const binding: Binding = {
        id,
        scope_id: context.scopeId,
        record_key: input.recordKey,
        credential: await this.credentials.seal(id, password),
        paste_name: null,
        version: 0,
      }
      const op = await this.operation(context.scopeId, input.requestId, id, "create", fingerprint, input.content, 0)
      try {
        await this.store.reserveCreate(binding, op)
      } catch {
        const raced = await this.store.operation(context.scopeId, input.requestId)
        return raced ? this.duplicate(raced, fingerprint) : this.error("RESERVATION_CONFLICT", op.id)
      }
      return await this.mutate(binding, op, input.content, password)
    } catch {
      return this.error("STORAGE_OR_CREDENTIAL_UNAVAILABLE", undefined, true)
    }
  }

  async updateContent(
    context: EntryContext,
    input: { entryId: string; requestId: string; expectedVersion: number; content: string },
  ): Promise<EntryResult> {
    if (
      !identifier(context.scopeId) ||
      !identifier(input.entryId) ||
      !identifier(input.requestId) ||
      typeof input.content !== "string" ||
      !Number.isSafeInteger(input.expectedVersion) ||
      input.expectedVersion < 1
    )
      return this.error("INVALID_INPUT")
    try {
      const binding = await this.store.get(context.scopeId, input.entryId)
      if (!binding) return this.error("ENTRY_NOT_FOUND")
      const fingerprint = await this.credentials.fingerprint(
        JSON.stringify(["update", context.scopeId, input.entryId, input.expectedVersion, input.content]),
      )
      const previous = await this.store.operation(context.scopeId, input.requestId)
      if (previous) return this.duplicate(previous, fingerprint)
      const password = await this.credentials.open(binding.id, binding.credential)
      const op = await this.operation(
        context.scopeId,
        input.requestId,
        input.entryId,
        "update",
        fingerprint,
        input.content,
        input.expectedVersion,
      )
      try {
        if (!(await this.store.reserveUpdate(op))) return this.error("VERSION_CONFLICT", op.id)
      } catch {
        const raced = await this.store.operation(context.scopeId, input.requestId)
        return raced ? this.duplicate(raced, fingerprint) : this.error("MUTATION_CONFLICT", op.id)
      }
      return await this.mutate(binding, op, input.content, password)
    } catch {
      return this.error("STORAGE_OR_CREDENTIAL_UNAVAILABLE", undefined, true)
    }
  }

  private async mutate(binding: Binding, op: Operation, content: string, password: string): Promise<EntryResult> {
    // Only the reservation owner can move reserved -> dispatched. Never steal a timed-out claim.
    if (!(await this.store.dispatch(op.id))) return this.error("MUTATION_CONFLICT", op.id)
    try {
      if (op.kind === "create") {
        binding.paste_name = await this.client.create(content, password)
        await this.store.rememberName(op, binding.paste_name)
      } else {
        await this.client.update(binding.paste_name!, password, content)
      }
      await this.client.permanent(binding.paste_name!)
      const entry = this.project(binding, op.expected_version + 1)
      await this.store.finish(op, JSON.stringify(entry))
      return { ok: true, entry }
    } catch {
      // If this write fails too, persisted 'dispatched' still prevents a blind retry.
      try {
        await this.store.uncertain(op.id)
      } catch {
        /* Remain fail-closed. */
      }
      return this.error("RECONCILIATION_REQUIRED", op.id)
    }
  }

  async readEntry(context: EntryContext, input: { entryId: string }): Promise<EntryResult> {
    if (!identifier(context.scopeId) || !identifier(input.entryId)) return this.error("INVALID_INPUT")
    try {
      const binding = await this.store.get(context.scopeId, input.entryId)
      if (!binding) return this.error("ENTRY_NOT_FOUND")
      if (!binding.paste_name || binding.version === 0 || (await this.store.pending(binding.id)))
        return this.error("RECONCILIATION_REQUIRED")
      await this.client.permanent(binding.paste_name)
      const content = await this.client.read(binding.paste_name)
      if (await this.store.pending(binding.id)) return this.error("MUTATION_CONFLICT")
      const current = await this.store.get(context.scopeId, input.entryId)
      if (current?.version !== binding.version) return this.error("VERSION_CONFLICT")
      return { ok: true, entry: this.project(binding), content }
    } catch (error) {
      return this.error(error instanceof PasteError ? error.code : "STORAGE_OR_CREDENTIAL_UNAVAILABLE", undefined, true)
    }
  }

  async reconcileEntry(context: EntryContext, input: { entryId: string }): Promise<EntryResult> {
    if (!identifier(context.scopeId) || !identifier(input.entryId)) return this.error("INVALID_INPUT")
    try {
      const binding = await this.store.get(context.scopeId, input.entryId)
      if (!binding) return this.error("ENTRY_NOT_FOUND")
      const pending = await this.store.pending(binding.id)
      if (!pending) return await this.readEntry(context, input)
      if (!binding.paste_name) return this.error("OPERATOR_RECONCILIATION_REQUIRED", pending.id)
      // A matching read alone cannot prove a timed-out PUT will not commit later.
      // Observe safely but keep the claim: no automatic unlock or mutation retry.
      await this.client.permanent(binding.paste_name)
      const content = await this.client.read(binding.paste_name)
      const matches = (await this.credentials.fingerprint(content)) === pending.content_fingerprint
      return this.error(
        matches ? "OUTCOME_OBSERVED_OPERATOR_CONFIRMATION_REQUIRED" : "RECONCILIATION_REQUIRED",
        pending.id,
      )
    } catch (error) {
      return this.error(error instanceof PasteError ? error.code : "STORAGE_OR_CREDENTIAL_UNAVAILABLE", undefined, true)
    }
  }
}
