import type { EntryContext, EntryResult, PublicEntry } from "../shared/entries"
import type { Credentials } from "./credentials"
import { PasteError } from "./paste-client"
import type { PasteClient } from "./paste-client"
import type { Binding, BindingStore, Operation } from "./store"

function identifier(value: unknown): value is string {
  return (
    typeof value === "string" &&
    value.length > 0 &&
    value.length <= 256 &&
    Array.from(value).every((char) => char.charCodeAt(0) >= 32)
  )
}

export class EntryService {
  constructor(
    private readonly store: BindingStore,
    private readonly credentials: Credentials,
    private readonly client: PasteClient,
  ) {}

  private error(code: string, correlationId: string = crypto.randomUUID(), retryable = false): EntryResult {
    return { ok: false, code, correlationId, retryable }
  }

  private project(binding: Binding, version = binding.version): PublicEntry {
    if (!binding.paste_name) throw new Error("ENTRY_NOT_READY")
    return {
      id: binding.id,
      pasteName: binding.paste_name,
      publicUrl: this.client.publicUrl(binding.paste_name),
      visibility: binding.visibility,
      retentionMode: binding.retention_mode,
      expiresAt: binding.expires_at,
      version,
    }
  }

  private duplicate(op: Operation, fingerprint: string): EntryResult {
    if (op.fingerprint !== fingerprint) return this.error("REQUEST_CONFLICT", op.id)
    if (op.status !== "succeeded" || !op.result) return this.error("RECONCILIATION_REQUIRED", op.id)
    // Results are generated by project(), never from upstream response objects.
    return { ok: true, entry: JSON.parse(op.result) as PublicEntry }
  }

  private async operation(
    scope: string,
    request: string,
    entry: string,
    kind: Operation["kind"],
    fingerprint: string,
    content: string,
    version: number,
  ): Promise<Operation> {
    return {
      id: crypto.randomUUID(),
      scope_id: scope,
      request_id: request,
      entry_id: entry,
      kind,
      fingerprint,
      content_fingerprint: await this.credentials.fingerprint(content),
      expected_version: version,
      status: "reserved",
      result: null,
    }
  }

  /** Phase 5 creates exactly one managed top-level unchecked task.  Refuse a
   * source with zero or multiple candidates instead of guessing among GFM. */
  private completeManagedTask(source: string): string | null {
    const candidates: number[] = []
    let offset = 0
    let fence: "`" | "~" | null = null
    for (const line of source.split(/(?<=\n)/)) {
      const fenceMatch = /^ {0,3}([`~])\1\1/.exec(line)
      if (fenceMatch) {
        if (!fence) fence = fenceMatch[1] as "`" | "~"
        else if (fence === fenceMatch[1]) fence = null
      } else if (!fence) {
        const task = /^(?:[-+*]|\d+[.)])\s+\[ \]/.exec(line)
        if (task) candidates.push(offset + task[0].indexOf("["))
      }
      offset += line.length
    }
    if (candidates.length !== 1) return null
    const candidate = candidates[0]
    return `${source.slice(0, candidate)}[x]${source.slice(candidate + 3)}`
  }

  /** Restore only Phase 5's one checked top-level managed task; do not guess
   * among nested tasks, prose, or fenced Markdown. */
  private restoreManagedTask(source: string): string | null {
    const candidates: number[] = []
    let offset = 0
    let fence: "`" | "~" | null = null
    for (const line of source.split(/(?<=\n)/)) {
      const fenceMatch = /^ {0,3}([`~])\1\1/.exec(line)
      if (fenceMatch) {
        if (!fence) fence = fenceMatch[1] as "`" | "~"
        else if (fence === fenceMatch[1]) fence = null
      } else if (!fence) {
        const task = /^(?:[-+*]|\d+[.)])\s+\[[xX]\]/.exec(line)
        if (task) candidates.push(offset + task[0].indexOf("["))
      }
      offset += line.length
    }
    if (candidates.length !== 1) return null
    const candidate = candidates[0]
    return `${source.slice(0, candidate)}[ ]${source.slice(candidate + 3)}`
  }

  async restoreEntry(context: EntryContext, input: { entryId: string; requestId: string }): Promise<EntryResult> {
    if (!identifier(context.scopeId) || !identifier(input.entryId) || !identifier(input.requestId))
      return this.error("INVALID_INPUT")
    try {
      const previous = await this.store.operation(context.scopeId, input.requestId)
      if (previous) {
        const kind = previous.kind === "restore_permanent" ? "restore_permanent" : "restore_timed"
        return this.duplicate(
          previous,
          await this.credentials.fingerprint(JSON.stringify([kind, context.scopeId, input.entryId])),
        )
      }
      const binding = await this.store.get(context.scopeId, input.entryId)
      if (!binding) return this.error("ENTRY_NOT_FOUND")
      const permanent =
        binding.visibility === "archived" && binding.retention_mode === "permanent" && binding.expires_at === null
      const timed =
        binding.visibility === "archived" &&
        binding.retention_mode === "timed" &&
        typeof binding.expires_at === "string" &&
        Number.isFinite(Date.parse(binding.expires_at))
      if (!permanent && !timed) return this.error("INVALID_LIFECYCLE_STATE")
      const kind = timed ? "restore_timed" : "restore_permanent"
      const fingerprint = await this.credentials.fingerprint(JSON.stringify([kind, context.scopeId, input.entryId]))
      const password = await this.credentials.open(binding.id, binding.credential)
      const source = await this.client.read(binding.paste_name!)
      const content = this.restoreManagedTask(source)
      if (content === null) return this.error("MANAGED_TASK_AMBIGUOUS")
      const op = await this.operation(
        context.scopeId,
        input.requestId,
        input.entryId,
        kind,
        fingerprint,
        content,
        binding.version,
      )
      try {
        if (!(timed ? await this.store.reserveTimedRestore(op) : await this.store.reservePermanentRestore(op)))
          return this.error("VERSION_CONFLICT", op.id)
      } catch {
        const raced = await this.store.operation(context.scopeId, input.requestId)
        return raced ? this.duplicate(raced, fingerprint) : this.error("MUTATION_CONFLICT", op.id)
      }
      if (!(await this.store.dispatch(op.id))) return this.error("MUTATION_CONFLICT", op.id)
      if (timed) {
        // This confirmed response is the expiry-cancellation boundary. The
        // checked source and archived deadline remain durable until it succeeds.
        try {
          await this.client.update(binding.paste_name!, password, source, "never")
        } catch (error) {
          if (error instanceof PasteError && (error.code === "UPSTREAM_REJECTED" || error.code === "ENTRY_NOT_FOUND")) {
            try {
              await this.store.fail(op.id)
            } catch {
              /* retain fail-closed evidence */
            }
            return this.error(error.code, op.id)
          }
          try {
            await this.store.uncertain(op.id)
          } catch {
            /* retain dispatched claim */
          }
          return this.error("RECONCILIATION_REQUIRED", op.id)
        }
      }
      try {
        await this.client.update(binding.paste_name!, password, content, "never")
        const active: Binding = { ...binding, visibility: "active", retention_mode: "permanent", expires_at: null }
        const entry = this.project(active, op.expected_version + 1)
        await this.store.finishPermanentRestore(op, JSON.stringify(entry))
        return { ok: true, entry }
      } catch (error) {
        if (error instanceof PasteError && (error.code === "UPSTREAM_REJECTED" || error.code === "ENTRY_NOT_FOUND")) {
          try {
            await this.store.fail(op.id)
          } catch {
            /* retain fail-closed evidence */
          }
          return this.error(error.code, op.id)
        }
        try {
          await this.store.uncertain(op.id)
        } catch {
          /* retain dispatched claim */
        }
        return this.error("RECONCILIATION_REQUIRED", op.id)
      }
    } catch (error) {
      return error instanceof PasteError
        ? this.error(error.code, undefined, error.code === "UPSTREAM_UNCERTAIN")
        : this.error("STORAGE_OR_CREDENTIAL_UNAVAILABLE", undefined, true)
    }
  }

  /**
   * Phase 7.2 compatibility entrypoint. This intentionally remains
   * permanent-only; the HTTP adapter uses restoreEntry for timed restores.
   */
  async restorePermanentEntry(
    context: EntryContext,
    input: { entryId: string; requestId: string },
  ): Promise<EntryResult> {
    if (!identifier(context.scopeId) || !identifier(input.entryId) || !identifier(input.requestId))
      return this.error("INVALID_INPUT")
    try {
      const fingerprint = await this.credentials.fingerprint(
        JSON.stringify(["restore_permanent", context.scopeId, input.entryId]),
      )
      const previous = await this.store.operation(context.scopeId, input.requestId)
      if (previous) return this.duplicate(previous, fingerprint)
      const binding = await this.store.get(context.scopeId, input.entryId)
      if (!binding) return this.error("ENTRY_NOT_FOUND")
      if (
        binding.visibility !== "archived" ||
        binding.retention_mode !== "permanent" ||
        binding.expires_at !== null
      )
        return this.error("INVALID_LIFECYCLE_STATE")
      return this.restoreEntry(context, input)
    } catch (error) {
      return error instanceof PasteError
        ? this.error(error.code, undefined, error.code === "UPSTREAM_UNCERTAIN")
        : this.error("STORAGE_OR_CREDENTIAL_UNAVAILABLE", undefined, true)
    }
  }

  async completeEntry(
    context: EntryContext,
    input: { entryId: string; requestId: string; action: "archive_permanent" | "archive_expiring" | "delete" },
  ): Promise<EntryResult | { ok: true; deleted: true }> {
    if (!identifier(context.scopeId) || !identifier(input.entryId) || !identifier(input.requestId))
      return this.error("INVALID_INPUT")
    try {
      const fingerprint = await this.credentials.fingerprint(
        JSON.stringify(["complete", context.scopeId, input.entryId, input.action]),
      )
      const previous = await this.store.operation(context.scopeId, input.requestId)
      if (previous) {
        if (previous.fingerprint !== fingerprint) return this.error("REQUEST_CONFLICT", previous.id)
        if (previous.status !== "succeeded") return this.error("RECONCILIATION_REQUIRED", previous.id)
        return input.action === "delete" ? { ok: true, deleted: true } : this.duplicate(previous, fingerprint)
      }
      const binding = await this.store.get(context.scopeId, input.entryId)
      if (!binding) return this.error("ENTRY_NOT_FOUND")
      const password = await this.credentials.open(binding.id, binding.credential)
      const source = input.action === "delete" ? "" : await this.client.read(binding.paste_name!)
      const content = input.action === "delete" ? "" : this.completeManagedTask(source)
      if (input.action !== "delete" && content === null) return this.error("MANAGED_TASK_AMBIGUOUS")
      const kind: Operation["kind"] =
        input.action === "archive_permanent"
          ? "complete_permanent"
          : input.action === "archive_expiring"
            ? "complete_expiring"
            : "delete"
      const op = await this.operation(
        context.scopeId,
        input.requestId,
        input.entryId,
        kind,
        fingerprint,
        content!,
        binding.version,
      )
      try {
        if (!(await this.store.reserveCompletion(op))) return this.error("VERSION_CONFLICT", op.id)
      } catch {
        const raced = await this.store.operation(context.scopeId, input.requestId)
        return raced
          ? raced.fingerprint === fingerprint
            ? input.action === "delete" && raced.kind === "delete" && raced.status === "succeeded"
              ? { ok: true, deleted: true }
              : this.duplicate(raced, fingerprint)
            : this.error("REQUEST_CONFLICT", raced.id)
          : this.error("MUTATION_CONFLICT", op.id)
      }
      if (!(await this.store.dispatch(op.id))) return this.error("MUTATION_CONFLICT", op.id)
      try {
        if (input.action === "delete") {
          await this.client.remove(binding.paste_name!, password)
          await this.store.finishDelete(op)
          return { ok: true, deleted: true }
        }
        const expiresAt = await this.client.update(
          binding.paste_name!,
          password,
          content!,
          input.action === "archive_expiring" ? "max" : "never",
        )
        if (input.action === "archive_expiring" && (!expiresAt || !Number.isFinite(Date.parse(expiresAt))))
          throw new PasteError("UPSTREAM_INVALID")
        const archived: Binding = {
          ...binding,
          visibility: "archived",
          retention_mode: input.action === "archive_expiring" ? "timed" : "permanent",
          expires_at: input.action === "archive_expiring" ? expiresAt : null,
        }
        const entry = this.project(archived, op.expected_version + 1)
        await this.store.finishCompletion(
          op,
          JSON.stringify(entry),
          "archived",
          archived.retention_mode,
          archived.expires_at,
        )
        return { ok: true, entry }
      } catch (error) {
        if (error instanceof PasteError && (error.code === "UPSTREAM_REJECTED" || error.code === "ENTRY_NOT_FOUND")) {
          try {
            await this.store.fail(op.id)
          } catch {
            /* preserve fail-closed evidence */
          }
          return this.error(error.code, op.id)
        }
        try {
          await this.store.uncertain(op.id)
        } catch {
          /* fail closed */
        }
        return this.error("RECONCILIATION_REQUIRED", op.id)
      }
    } catch (error) {
      return error instanceof PasteError
        ? this.error(error.code, undefined, error.code === "UPSTREAM_UNCERTAIN")
        : this.error("STORAGE_OR_CREDENTIAL_UNAVAILABLE", undefined, true)
    }
  }

  async createEntry(
    context: EntryContext,
    input: { recordKey: string; requestId: string; content: string },
  ): Promise<EntryResult> {
    if (
      !identifier(context.scopeId) ||
      !identifier(input.recordKey) ||
      !identifier(input.requestId) ||
      typeof input.content !== "string"
    )
      return this.error("INVALID_INPUT")
    try {
      const fingerprint = await this.credentials.fingerprint(
        JSON.stringify(["create", context.scopeId, input.recordKey, input.content]),
      )
      const existing = await this.store.operation(context.scopeId, input.requestId)
      if (existing) return this.duplicate(existing, fingerprint)
      const id = crypto.randomUUID()
      const password = this.credentials.generate()
      const binding: Binding = {
        id,
        scope_id: context.scopeId,
        record_key: input.recordKey,
        credential: await this.credentials.seal(id, password),
        paste_name: null,
        visibility: "active",
        retention_mode: "permanent",
        expires_at: null,
        version: 0,
      }
      const op = await this.operation(context.scopeId, input.requestId, id, "create", fingerprint, input.content, 0)
      try {
        await this.store.reserveCreate(binding, op)
      } catch {
        const raced = await this.store.operation(context.scopeId, input.requestId)
        return raced ? this.duplicate(raced, fingerprint) : this.error("RESERVATION_CONFLICT", op.id)
      }
      return await this.mutate(binding, op, input.content, password)
    } catch {
      return this.error("STORAGE_OR_CREDENTIAL_UNAVAILABLE", undefined, true)
    }
  }

  async updateContent(
    context: EntryContext,
    input: { entryId: string; requestId: string; expectedVersion: number; content: string },
  ): Promise<EntryResult> {
    if (
      !identifier(context.scopeId) ||
      !identifier(input.entryId) ||
      !identifier(input.requestId) ||
      typeof input.content !== "string" ||
      !Number.isSafeInteger(input.expectedVersion) ||
      input.expectedVersion < 1
    )
      return this.error("INVALID_INPUT")
    try {
      const binding = await this.store.get(context.scopeId, input.entryId)
      if (!binding) return this.error("ENTRY_NOT_FOUND")
      const fingerprint = await this.credentials.fingerprint(
        JSON.stringify(["update", context.scopeId, input.entryId, input.expectedVersion, input.content]),
      )
      const previous = await this.store.operation(context.scopeId, input.requestId)
      if (previous) return this.duplicate(previous, fingerprint)
      const password = await this.credentials.open(binding.id, binding.credential)
      const op = await this.operation(
        context.scopeId,
        input.requestId,
        input.entryId,
        "update",
        fingerprint,
        input.content,
        input.expectedVersion,
      )
      try {
        if (!(await this.store.reserveUpdate(op))) return this.error("VERSION_CONFLICT", op.id)
      } catch {
        const raced = await this.store.operation(context.scopeId, input.requestId)
        return raced ? this.duplicate(raced, fingerprint) : this.error("MUTATION_CONFLICT", op.id)
      }
      return await this.mutate(binding, op, input.content, password)
    } catch {
      return this.error("STORAGE_OR_CREDENTIAL_UNAVAILABLE", undefined, true)
    }
  }

  private async mutate(binding: Binding, op: Operation, content: string, password: string): Promise<EntryResult> {
    // Only the reservation owner can move reserved -> dispatched. Never steal a timed-out claim.
    if (!(await this.store.dispatch(op.id))) return this.error("MUTATION_CONFLICT", op.id)
    try {
      if (op.kind === "create") {
        binding.paste_name = await this.client.create(content, password)
        await this.store.rememberName(op, binding.paste_name)
      } else {
        await this.client.update(binding.paste_name!, password, content)
      }
      await this.client.permanent(binding.paste_name!)
      const entry = this.project(binding, op.expected_version + 1)
      await this.store.finish(op, JSON.stringify(entry))
      return { ok: true, entry }
    } catch {
      // If this write fails too, persisted 'dispatched' still prevents a blind retry.
      try {
        await this.store.uncertain(op.id)
      } catch {
        /* Remain fail-closed. */
      }
      return this.error("RECONCILIATION_REQUIRED", op.id)
    }
  }

  async readEntry(context: EntryContext, input: { entryId: string }): Promise<EntryResult> {
    if (!identifier(context.scopeId) || !identifier(input.entryId)) return this.error("INVALID_INPUT")
    try {
      const binding = await this.store.get(context.scopeId, input.entryId)
      if (!binding) return this.error("ENTRY_NOT_FOUND")
      if (!binding.paste_name || binding.version === 0 || (await this.store.pending(binding.id)))
        return this.error("RECONCILIATION_REQUIRED")
      await this.client.permanent(binding.paste_name, binding.retention_mode === "timed" ? binding.expires_at : null)
      const content = await this.client.read(binding.paste_name)
      if (await this.store.pending(binding.id)) return this.error("MUTATION_CONFLICT")
      const current = await this.store.get(context.scopeId, input.entryId)
      if (current?.version !== binding.version) return this.error("VERSION_CONFLICT")
      return { ok: true, entry: this.project(binding), content }
    } catch (error) {
      return this.error(error instanceof PasteError ? error.code : "STORAGE_OR_CREDENTIAL_UNAVAILABLE", undefined, true)
    }
  }

  async reconcileEntry(context: EntryContext, input: { entryId: string }): Promise<EntryResult> {
    if (!identifier(context.scopeId) || !identifier(input.entryId)) return this.error("INVALID_INPUT")
    try {
      const binding = await this.store.get(context.scopeId, input.entryId)
      if (!binding) return this.error("ENTRY_NOT_FOUND")
      const pending = await this.store.pending(binding.id)
      if (!pending) return await this.readEntry(context, input)
      if (!binding.paste_name) return this.error("OPERATOR_RECONCILIATION_REQUIRED", pending.id)
      // A matching read alone cannot prove a timed-out PUT will not commit later.
      // Observe safely but keep the claim: no automatic unlock or mutation retry.
      await this.client.permanent(binding.paste_name, binding.retention_mode === "timed" ? binding.expires_at : null)
      const content = await this.client.read(binding.paste_name)
      const matches = (await this.credentials.fingerprint(content)) === pending.content_fingerprint
      return this.error(
        matches ? "OUTCOME_OBSERVED_OPERATOR_CONFIRMATION_REQUIRED" : "RECONCILIATION_REQUIRED",
        pending.id,
      )
    } catch (error) {
      return this.error(error instanceof PasteError ? error.code : "STORAGE_OR_CREDENTIAL_UNAVAILABLE", undefined, true)
    }
  }
}
