import { expect, it, describe } from "vitest"
import { createExecutionContext, waitOnExecutionContext } from "cloudflare:test"
import { genRandomBlob, upload, uploadExpectStatus, workerFetch, BASE_URL } from "./testUtils.js"

describe("max reads (r)", () => {
  it("rejects invalid r", async () => {
    const ctx = createExecutionContext()
    const blob = genRandomBlob(32)
    await uploadExpectStatus(ctx, { c: blob, r: "0" }, 400)
    await uploadExpectStatus(ctx, { c: blob, r: "-1" }, 400)
    await uploadExpectStatus(ctx, { c: blob, r: "abc" }, 400)
    await uploadExpectStatus(ctx, { c: blob, r: "1001" }, 400)
  })

  it("allows one content GET when r=1 then 404", async () => {
    const ctx = createExecutionContext()
    const blob = genRandomBlob(64)
    const created = await upload(ctx, { c: blob, r: "1" })
    const first = await workerFetch(ctx, created.url)
    expect(first.status).toStrictEqual(200)
    expect(first.headers.get("Cache-Control")).toStrictEqual("no-store")
    expect(new Uint8Array(await first.arrayBuffer())).toStrictEqual(new Uint8Array(await blob.arrayBuffer()))
    await waitOnExecutionContext(ctx)

    const secondCtx = createExecutionContext()
    const second = await workerFetch(secondCtx, created.url)
    expect(second.status).toStrictEqual(404)
    await waitOnExecutionContext(secondCtx)
  })

  it("allows two content GETs when r=2 then 404", async () => {
    const ctx = createExecutionContext()
    const blob = genRandomBlob(32)
    const created = await upload(ctx, { c: blob, r: "2" })
    expect((await workerFetch(ctx, created.url)).status).toStrictEqual(200)
    await waitOnExecutionContext(ctx)
    const ctx2 = createExecutionContext()
    expect((await workerFetch(ctx2, created.url)).status).toStrictEqual(200)
    await waitOnExecutionContext(ctx2)
    const ctx3 = createExecutionContext()
    expect((await workerFetch(ctx3, created.url)).status).toStrictEqual(404)
    await waitOnExecutionContext(ctx3)
  })

  it("does not consume HEAD or metadata GET", async () => {
    const ctx = createExecutionContext()
    const blob = genRandomBlob(32)
    const created = await upload(ctx, { c: blob, r: "1" })
    const name = new URL(created.url).pathname.slice(1)

    const head = await workerFetch(ctx, new Request(created.url, { method: "HEAD" }))
    expect(head.status).toStrictEqual(200)
    await waitOnExecutionContext(ctx)

    const metaCtx = createExecutionContext()
    const meta = await workerFetch(metaCtx, `${BASE_URL}/m/${name}`)
    expect(meta.status).toStrictEqual(200)
    await waitOnExecutionContext(metaCtx)

    const getCtx = createExecutionContext()
    expect((await workerFetch(getCtx, created.url)).status).toStrictEqual(200)
    await waitOnExecutionContext(getCtx)
    const gone = createExecutionContext()
    expect((await workerFetch(gone, created.url)).status).toStrictEqual(404)
    await waitOnExecutionContext(gone)
  })

  it("skips display SSR body for read-limited pastes and does not consume on /d/", async () => {
    const ctx = createExecutionContext()
    const created = await upload(ctx, { c: "hello-limited", r: "1" })
    const name = new URL(created.url).pathname.slice(1)
    const display = await workerFetch(ctx, `${BASE_URL}/d/${name}`)
    expect(display.status).toStrictEqual(200)
    const html = await display.text()
    expect(html).not.toContain("hello-limited")
    expect(html).not.toContain("__PASTE_DATA__")
    await waitOnExecutionContext(ctx)

    const getCtx = createExecutionContext()
    const raw = await workerFetch(getCtx, created.url)
    expect(raw.status).toStrictEqual(200)
    expect(await raw.text()).toStrictEqual("hello-limited")
    await waitOnExecutionContext(getCtx)
  })

  it("serializes concurrent r=1 content GETs to a single 200", async () => {
    const ctx = createExecutionContext()
    const blob = genRandomBlob(32)
    const created = await upload(ctx, { c: blob, r: "1" })
    await waitOnExecutionContext(ctx)

    const a = createExecutionContext()
    const b = createExecutionContext()
    const [ra, rb] = await Promise.all([workerFetch(a, created.url), workerFetch(b, created.url)])
    const statuses = [ra.status, rb.status].sort()
    expect(statuses).toStrictEqual([200, 404])
    await waitOnExecutionContext(a)
    await waitOnExecutionContext(b)
  })

  it("consumes /a/ article GET", async () => {
    const ctx = createExecutionContext()
    const created = await upload(ctx, { c: "# hi\n", r: "1" })
    const name = new URL(created.url).pathname.slice(1)
    const article = await workerFetch(ctx, `${BASE_URL}/a/${name}`)
    expect(article.status).toStrictEqual(200)
    await waitOnExecutionContext(ctx)
    const gone = createExecutionContext()
    expect((await workerFetch(gone, created.url)).status).toStrictEqual(404)
    await waitOnExecutionContext(gone)
  })

  it("PUT without r clears max-reads", async () => {
    const ctx = createExecutionContext()
    const blob = genRandomBlob(16)
    const created = await upload(ctx, { c: blob, r: "1" })
    await upload(ctx, { c: blob }, { method: "PUT", url: created.manageUrl })
    expect((await workerFetch(ctx, created.url)).status).toStrictEqual(200)
    await waitOnExecutionContext(ctx)
    const ctx2 = createExecutionContext()
    expect((await workerFetch(ctx2, created.url)).status).toStrictEqual(200)
    await waitOnExecutionContext(ctx2)
  })

  it("PUT with r starts a new read counter", async () => {
    const ctx = createExecutionContext()
    const blob = genRandomBlob(16)
    const created = await upload(ctx, { c: blob, r: "2" })
    expect((await workerFetch(ctx, created.url)).status).toStrictEqual(200)
    await waitOnExecutionContext(ctx)
    await upload(ctx, { c: blob, r: "2" }, { method: "PUT", url: created.manageUrl })
    const a = createExecutionContext()
    expect((await workerFetch(a, created.url)).status).toStrictEqual(200)
    await waitOnExecutionContext(a)
    const b = createExecutionContext()
    expect((await workerFetch(b, created.url)).status).toStrictEqual(200)
    await waitOnExecutionContext(b)
    const c = createExecutionContext()
    expect((await workerFetch(c, created.url)).status).toStrictEqual(404)
    await waitOnExecutionContext(c)
  })

  it("consumes /u/ redirect GET", async () => {
    const ctx = createExecutionContext()
    const created = await upload(ctx, { c: "https://example.com/x", r: "1" })
    const name = new URL(created.url).pathname.slice(1)
    const redirect = await workerFetch(ctx, `${BASE_URL}/u/${name}`)
    expect(redirect.status).toStrictEqual(302)
    await waitOnExecutionContext(ctx)
    const gone = createExecutionContext()
    expect((await workerFetch(gone, created.url)).status).toStrictEqual(404)
    await waitOnExecutionContext(gone)
  })

  it("ignores Range on read-limited pastes and still consumes once", async () => {
    const ctx = createExecutionContext()
    const blob = genRandomBlob(32)
    const created = await upload(ctx, { c: blob, r: "1" })
    const ranged = await workerFetch(ctx, new Request(created.url, { headers: { Range: "bytes=0-3" } }))
    expect(ranged.status).toStrictEqual(200)
    expect(ranged.headers.get("Content-Range")).toBeNull()
    expect(ranged.headers.get("Cache-Control")).toStrictEqual("no-store")
    expect(new Uint8Array(await ranged.arrayBuffer())).toStrictEqual(new Uint8Array(await blob.arrayBuffer()))
    await waitOnExecutionContext(ctx)
    const gone = createExecutionContext()
    expect((await workerFetch(gone, created.url)).status).toStrictEqual(404)
    await waitOnExecutionContext(gone)
  })

  it("leaves unlimited pastes readable more than once", async () => {
    const ctx = createExecutionContext()
    const blob = genRandomBlob(16)
    const created = await upload(ctx, { c: blob })
    expect((await workerFetch(ctx, created.url)).status).toStrictEqual(200)
    await waitOnExecutionContext(ctx)
    const ctx2 = createExecutionContext()
    expect((await workerFetch(ctx2, created.url)).status).toStrictEqual(200)
    expect((await workerFetch(ctx2, created.url)).headers.get("Cache-Control")).not.toStrictEqual("no-store")
    await waitOnExecutionContext(ctx2)
  })
})
